A = {};
A.leaves = [
"-itos",
"12th grade",
"3rd grade",
"8th grade",
"acibitually flirting",
"activities",
"acts of service",
"affirmation",
"ambition",
"american football",
"amity",
"animals",
"Another damn of the damns you're not giving",
"apricots",
"costume anxiety",
"battery anxiety",
"sleeplessness anxiety",
"April",
"art",
"Artificial Intelligence",
"Aung San Suu Kyi",
"azure",
"back massage",
"baked potatoes",
"beach",
"beauty",
"beef",
"beer",
"being on bottom",
"being on top",
"black tea",
"blue",
"blushing",
"boiled potatoes",
"burnt sienna",
"cabernet sauvignon",
"cabin",
"camera obscurae",
"campfires",
"cantaloupe",
"capitalism",
"cardinal",
"cartwheels",
"cats",
"cerulean",
"Cheetos",
"chicken",
"cinnamon",
"cleaning a stranger's poop off your doorstep",
"cocktails",
"coffee",
"college",
"colors",
"compassion",
"confidence",
"conscientious",
"credit unions",
"crepuscular",
"crimson",
"cuddling",
"cyan",
"dancing",
"daylight saving time",
"December",
"delight",
"democracy",
"desert",
"dogs",
"dominance",
"Doritos",
"Dorothy Parker",
"drug tests",
"ecru",
"ellipses",
"em dashes",
"emerald",
"emotions",
"empathy",
"en dashes",
"enmity",
"ephemera",
"EQ tests",
"euphoria",
"excellent food",
"excellent music",
"extraversion",
"eyelashes",
"February",
"feeling",
"femininity",
"film",
"financial security",
"fish",
"flavors",
"flirting",
"folk",
"foot massage",
"forest",
"Frederick Douglas",
"Fritos",
"fuchsia",
"fun",
"gender fluidity",
"getting down",
"gifts",
"gin",
"ginger beer",
"giving anal",
"giving oral",
"glute massage",
"gluten",
"goosebumps",
"green",
"green tea",
"habitually ambiguous flirting",
"hamstring massage",
"hand massage",
"handstands",
"Harriet Tubman",
"head massage",
"hearts",
"heights",
"herbal tea",
"herringbone",
"hip hop",
"Homesteading",
"honesty",
"houndstooth",
"hugs",
"indigo",
"Infidels, Jezebels, Salomes and Delilahs",
"inimical",
"inimitable",
"inside jokes",
"integrity",
"intelligence",
"introversion",
"intuition",
"IPAs",
"isolation",
"It beggars the belief sometimes What thieves the lovers be",
"January",
"roasted potatoes",
"judging",
"July",
"karaoke",
"kindness",
"kink",
"kisses",
"lakes",
"lamb",
"lavender",
"leadership",
"life itself",
"long letters",
"long shadows",
"loud bars",
"loud construction",
"loud motorcycles",
"love languages",
"loyalty",
"lust",
"made-up games with ambiguous rules",
"Mae West",
"magenta",
"malbec",
"manscaping",
"mansplaining",
"manspreading",
"masculinity",
"mashed potatoes",
"massages",
"masturbation",
"merlot",
"mice",
"mischief",
"missionary",
"monster ballads",
"mosquitos",
"mountains",
"moxie",
"mushrooms",
"music",
"Myers Briggs",
"nectarines",
"nightswimming",
"November",
"nuns",
"nytimes",
"Obama",
"October",
"olive green",
"optimism",
"orange",
"oxblood",
"parisien blue",
"passion",
"patios",
"people",
"people intolerant of other people's cultures",
"perceiving",
"periwinkle",
"personality tests",
"petrichor",
"physical touch",
"pinot noir",
"Placer County",
"Planned Parenthood",
"polka dots",
"Pope Francis",
"portmanteaus",
"potatoes",
"present company",
"Programmers robotifying serendipitous pleasures",
"prussian blue",
"punk",
"quadricep massage",
"quality time",
"randomness",
"raspberries",
"reason",
"receiving anal",
"receiving oral",
"red",
"red wine",
"rejection",
"restraints",
"rock",
"Rorschach tests",
"rosemary",
"ruby",
"scarlet",
"science",
"self-inflicted physical suffering",
"sensing",
"sex",
"shame",
"shoulder massage",
"size",
"skepticism",
"skinnydipping",
"Soaking in hot water on a cold day",
"Sorry all your fish are dead. I still like you though.",
"spanking",
"sphinxlike",
"sprinting",
"standardized tests",
"STD tests",
"stripes",
"suffering",
"swagger",
"sweaty sex",
"Swimming in cool water on a hot day",
"tantra",
"taupe",
"tent",
"the ACLU",
"the best day of your life",
"The Dutch",
"the future",
"The Notorious B.I.G.",
"The Notorious R.G.B.",
"the sunny side of the street",
"the tragically hip",
"thinking",
"this song",
"this weather",
"today",
"tofu",
"triumph",
"trust",
"turmeric",
"turquoise",
"unburnt sienna",
"unnecessary honesty",
"verve",
"violet",
"whiskey",
"white wine",
"wit",
"womanscaping",
"words",
"yellow",
"yoga",
"your mom",
"zeal",
"unicorns",
"butterflies",
"anonymity",
"unanimity",
"incognito mode",
"Preferences",
"defining the relationship",
"southern exposure",
"difficult questions",
"Fusion is the broken heart that’s lonely’s only thought",
'"Ooh la-la"s, "Oh, hell yes"es, "I can\'t wait"s, "I gotta see you again"ses.',
"Punctured bicycle, on a hillside, desolate",
"Your shoulder blade, your spine Were shorelines in the moon light",
"Somersaults across the lawn Singing dancing up till dawn",
"A nation with their freezers full Are dancing in their seats While outside another nation Is sleeping in the streets",
"Calling time and temperature just for some company",
"I wish you were here; I wish I was too",
"Richard Wagner's letters to his lover Mathilde",
"Kafka in his letters to his lover Milena",
"Vienna in a fugue-state workin' on a thing That when he finished took almost seven hours to sing",
"Allergic to the counterfeit, impartial to the politics",
"The hootin-'n-da-hollerin, back-'n-forth-wit-da-arguin' Where-you-from who-you-know what-you-make what-kind-of-car-you-in",
"Unhappy with the riches cause you're piss poor morally",
"Ignorin' all prior advice and forewarnin' We mighty full of ourselves all of a sudden, aren't we?",
"Smoother than the glass that the sea spits out",
"Not a player nor a player hater, just a bookworm on a respirator",
"Didn't have a dalliance much less a hot tub; was just a brain whose brain never let up",
"The twelve years after five Are years we're lucky to survive",
"Not funny like on TV and not smart like it is in books",
"The people chained up in the cave In the allegory of the people in the cave by the Greek guy",
];
